spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nexis_db
    username: nexis_user
    password: nexis_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  cors:
    allowed-origin: http://localhost:5173